#!/bin/sh -efu

# distro template
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021, Leonid Krivoshein <klark@altlinux.org>
#

# Alias
short="dist"

# Required top-level directory
entity="Distros"

# Required ID's in the path
ids="dID"

# Editable templates
templates="distro.yml=@dID@.yml"

