#!/bin/sh -efu

# check on the server-side
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021-2022, Leonid Krivoshein <klark@altlinux.org>
#

. "$CSS_LIBDIR"/csi-server-common

optlist="${1-}"

chk_repo_msg 'draft'
run rm -f -- "$HOME"/SUCCESS
run "$chktree_cmd" $optlist && [ -f "$HOME"/SUCCESS ]
run rm -f -- "$HOME"/SUCCESS

debug "script finished"

