[Новый партнёр: %s]
1:^Vendors/([^\/]+)/contacts\.yml$
1:^Vendors/([^\/]+)/events\.yml$
1:^Vendors/([^\/]+)/vendor\.yml$

[Новый партнёр: %s]
1:^Vendors/([^\/]+)/contacts\.yml$
1:^Vendors/([^\/]+)/vendor\.(jpg|png)$
1:^Vendors/([^\/]+)/vendor\.yml$

[Новый сертификат c %s от %s|newcert]
3:^Vendors/([^\/]+)/([^\/]+)/CI/([0-9]+)\.yml$
2:^Vendors/([^\/]+)/([^\/]+)/CI/cert\.(jpg|pdf)$
2:^Vendors/([^\/]+)/([^\/]+)/CI/number$

