[Удалены файлы партнёра: %s]
1:^Vendors/([^\/]+)/contacts\.yml$
1:^Vendors/([^\/]+)/vendor\.yml$

[Удалены файлы партнёра: %s]
1:^Vendors/([^\/]+)/events\.yml$
1:^Vendors/([^\/]+)/vendor\.yml$

[Удалены файлы продукта %s: %s]
2:^Vendors/([^\/]+)/([^\/]+)/product\.(jpg|png)$
2:^Vendors/([^\/]+)/([^\/]+)/product\.yml$

[Удалены файлы версии продукта %s %s: %s]
3:^Vendors/([^\/]+)/([^\/]+)/VERS/([^\/]+)/version\.(jpg|png)$
3:^Vendors/([^\/]+)/([^\/]+)/VERS/([^\/]+)/version\.yml$

