#!/bin/sh -efu

# log on client-side
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021, Leonid Krivoshein <klark@altlinux.org>
#

action_summary() {
	echo "  log       Shows log after last upload in the 'local' repository."
}

do_log() {
	local oldtag=

	[ ! -s "$cfgdir"/TAG ] ||
		read -r oldtag <"$cfgdir"/TAG 2>/dev/null ||:
	check_local_repo

	if [ -n "$oldtag" ]; then
		run git log "$oldtag"..
	else
		run git log
	fi
}

