#!/bin/sh -efu

# nxcert on client-side
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021-2022, Leonid Krivoshein <klark@altlinux.org>
#

action_summary() {
	echo "  nxcert    Shows next certificate number for specified year."
}

year=

action_parse_args() {
	if [ -z "${1-}" ]; then
		year="$(date +%Y)"
	elif [ "${1-}" = help ] || [ "$#" != 1 ]; then
		echo "Usage: $progname $action [<YYYY>]"
		exit 0
	else
		echo "$1" |grep -qsE -- '^20[0-9][0-9]$' ||
			fatal "invalid year, <20YY> expected."
		year="$1"
	fi
}

do_nxcert() {
	local number

	check_local_repo

	if [ ! -d "Legal/$year/certs.d" ]; then
		number=1
	else
		number="$(set +f; awk '{print $1;}' \
				"Legal/$year"/certs.d/*.lst 2>/dev/null |
				grep -sE '^[1-9]' |sort -n |tail -n1)"
		[ -z "$number" ] && number=1 || number=$((1 + $number))
	fi

	printf "%s\n" "$number"
}

