#!/bin/sh -efu

# reset on client-side
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021, Leonid Krivoshein <klark@altlinux.org>
#

action_summary() {
	echo "  reset     Resets 'local' and 'draft' repositories."
}

do_reset() {
	local oldtag=

	check_local_repo
	read -r oldtag <"$cfgdir"/TAG 2>/dev/null && [ -n "$oldtag" ] ||
		fatal "can't reset 'local' CSI repository."

	# Continue on the server-side
	server_side reset $quiet "$oldtag"

	message "Resetting 'local' CSI repository..."
	run git reset --hard $quiet "$oldtag"
	run sync
	message "Last upload tag name is '$oldtag'."
}

