#!/bin/sh -efu

# status on client-side
#
# This file is covered by the GNU General Public License
# version 3, or (at your option) any later version, which
# should be included with sources as the file COPYING.
#
# Copyright (C) 2021, Leonid Krivoshein <klark@altlinux.org>
#

action_summary() {
	echo "  status    Shows the status of the 'local' CSI repository."
}

do_status() {
	check_local_repo
	run git status
}

